server:
  port: 8200

spring:
  application:
    name: wfs
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
      - id: brms-route
        uri: http://localhost:8050
        predicates:
        - Path=/brms/**